algoritmo "semnome"
var
   M: Vetor [1..3, 1..2] de Inteiro
   L, C: Inteiro
inicio
     Para L <- 1 ate 3 faca
        Para C <- 1 ate 2 faca
           Escreva("Digite o valor da posição [", l ,",", c ," ]:")
           Leia(M[L,C])
        FimPara
     FimPara
     
     Para L <- 1 ate 3 faca
        Para C <- 1 ate 2 faca
           Escreva(M[L,C]:5)
        FimPara
        Escreval()
     FimPara
fimalgoritmo